Adding additional commands for controling HDMI switch configuration.
krohrbaugh/teeheesmart pull request #1
Opened 2024-12-18 00:52 UTC by barndawgie

I'd like to be able to tinker with my 8-port HDMI switch's configuration from Home Assistant, so would love to add these additional commands to teeheesmart.

2024-12-18 03:02 UTC, krohrbaugh requested changes
Thanks for working on this!

I've left a few comments requesting a few readability changes, but overall looks great.

Sorry about the linting nitpick comments. I need to setup a linter on this project, but haven't yet. 🙃

2024-12-18 03:02 UTC, krohrbaugh commented on src/teeheesmart/hex/media_switch.py
> +  def set_buzzer_mute (self, input: bool) -> None:
Let's use more descriptive parameter names for the data here. It's `input` in `select_source` because it's specifying an HDMI input.

Additionally, please remove the white space between the method name and the opening param.

Something like:

`def set_buzzer_mute(self, is_buzzer_muted: bool) -> None`

2024-12-18 03:02 UTC, krohrbaugh commented on src/teeheesmart/hex/media_switch.py
> +  def set_led_timeout (self, input: int) -> None:
Same as above: Let's use more descriptive parameter names for the data here.

Additionally, please remove the white space between the method name and the opening param.

Something like:

`def set_led_timeout(self, timeout_sec: int) -> None`

2024-12-18 03:02 UTC, krohrbaugh commented on src/teeheesmart/hex/media_switch.py
> +      normalized_input = 30
We could make it clearer that the only valid values for this are  `0`, `10`, or `30`.

What do you think about the following?

```
normalized_timeout_sec = timeout_sec
if normalized_timeout_sec not in [0, 10, 30]:
  normalized_timeout_sec = 30
```

2024-12-18 03:02 UTC, krohrbaugh commented on src/teeheesmart/hex/media_switch.py
> +  def set_input_detection (self, input: bool) -> None:
Let's change the method name so it's clearer what the boolean does, as well as make the parameter name more descriptive. Additionally, please remove the white space between the method name and the opening param. 

Something like:

`def auto_detect_source(self, is_enabled: bool) -> None:`

2024-12-18 07:01 UTC, barndawgie commented on src/teeheesmart/hex/media_switch.py
> +      normalized_input = 30
I thought of creating an ENUM but felt it was overkill - this does feel cleaner though.

2024-12-18 07:02 UTC, barndawgie commented
I'm not very experienced with Python so I really appreciate the feedback! I Just checked in changes that I hope address it all.

I can take a stab at a basic linting config though not sure there is much more to add there - this is all of the calls that are in the doc I have, anyway!

2025-01-04 10:55 UTC, barndawgie commented
@krohrbaugh - Hopefully those changes cover everything you were looking for? They were the best names I could come up with. I did wonder if `enable_buzzer` and `disable_buzzer` methods might have been cleaner from a naming perspective but they seemed a bit odd semantically.

2025-01-14 01:11 UTC, barndawgie commented
@krohrbaugh - Any chance you could take another look here? Was hoping to get started on my home-assistant side changes soon.

2025-01-17 02:58 UTC, krohrbaugh commented
Sorry about my delay in responding. I had a family emergency that kept me from responding here.

All looks good, so I'll go ahead and merge, and then do a release.

Thank you for sticking with this!

2025-01-17 03:01 UTC, merged

2025-01-17 03:02 UTC, krohrbaugh reviewed
👍

2025-01-17 03:15 UTC, barndawgie commented
Thank you! Excited to contribute to another project.